language: node_js
node_js:
- 16.13.1
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - me@hurkanyakay.com
    on_success: always
    on_failure: always
  slack: ouroboros-rocks:r8wyjrwUG95cQoiShc2UP4km
before_script:
- yarn
script:
- yarn install --frozen-lockfile
- yarn clean
- yarn build
- yarn test:e2e:prod
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/travis_rsa -d
- ssh-keyscan -H $REMOTE_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: "./scripts/deploy.sh"
  on:
    branch: master