language: node_js
node_js:
- 10.8
dist: trusty
sudo: false
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
  - node_modules
  override:
  - npm ci
  - npm run cy:verify
notifications:
  email:
    recipients:
    - me@hurkanyakay.com
    on_success: always
    on_failure: always
script:
- npm run test:e2e:dev
- npm run build
- npm run test:e2e:prod
before_install:
- openssl aes-256-cbc -K $encrypted_9cd34e805391_key -iv $encrypted_9cd34e805391_iv
  -in travis_rsa.enc -out travis_rsa -d

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true