name: Build and Deploy
on:
  push:
    branches: master      


jobs:
  build-and-deploy:
    name: Build and deploy portfolio site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Run project in background
        working-directory: packages/client
        run: |
          yarn install --frozen-lockfile &
          yarn clean &
          yarn cy:install &
          yarn build 
        env:
          PORT: 9000

      - name: Test Project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: cy:run:prod