name: Build and Deploy
on:
  push:
    branches: master      


jobs:
  build-and-deploy:
    name: Build and deploy portfolio site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Run project in background
        run: |
          yarn install --frozen-lockfile &&
          yarn clean &&
          yarn cy:install &&
          yarn build &&
          yarn test:e2e:prod
        env:
          PORT: 9000



   