name: Build and Deploy
on:
  push:
    branches: master      


jobs:
  build-and-deploy:
    name: Build and deploy portfolio site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          text: overwrite text
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
    
      # - name: Run project in background
      #   run: |
      #     yarn install --frozen-lockfile &&
      #     yarn clean &&
      #     yarn cy:install &&
      #     yarn build &&
      #     yarn test:e2e:prod
      #   env:
      #     PORT: 9000
      - name: Install
        run: |
          yarn install --frozen-lockfile
          yarn clean &&
          
      - name: Build
        run: |
          yarn build
     
      - name: Test
        run: |
          yarn test:e2e:prod
        env:
          PORT: 9000


   